project_id = "bnaqcsjummrfdwdmppkm"

[functions.send-booking-email]
verify_jwt = false

[functions.push-subscribe]
verify_jwt = false

[functions.push-unsubscribe]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-push-notification-all]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.booking-reminders]
verify_jwt = false

[functions.inactive-users-reminder]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.rating-reminders]
verify_jwt = false

[functions.scan-loyalty-qr]
verify_jwt = false

[functions.auto-credit-loyalty]
verify_jwt = false
